### ISSUE TITLE
pip install fail on Mac

### ISSUE THREAD

**Issue by GeekMe93** [src-d/lapjv#1]
Hi, use pip to install but it failed:

What I use:

source activate root
pip install lapjv

<img width="784" alt="screenshot 2017-04-08 21 22 55" src="https://cloud.githubusercontent.com/assets/15790176/24829304/92b3b88c-1ca1-11e7-86e6-966956511d78.png">

**Comment by vmarkovtsev** [comment]
It is not clear from the screenshot, but is it python 2.x? It is officially not supported, sorry.

**Comment by GeekMe93** [comment]
@vmarkovtsev  Hi, I use python3 in anaconda. I attached another photo. Any solution?

Thanks !

<img width="774" alt="screenshot 2017-04-08 21 32 05" src="https://cloud.githubusercontent.com/assets/15790176/24829378/e46d43b8-1ca2-11e7-897e-364c3601a460.png">

**Comment by qiliux** [comment]
When install in windows anaconda , error also occered .
![image](https://cloud.githubusercontent.com/assets/24810193/25003060/23175b9a-2080-11e7-9f1b-be44131a7c76.png)

**Comment by vmarkovtsev** [comment]
I am back from the vacation, fresh and already installing clean VMs with macOS and Windows to debug these problems. Will fix ASAP. The only difference I've noticed so far is that I am using xcode cmdline tools 7.3 and not the latest 8.2.

**Comment by vmarkovtsev** [comment]
@GeekMe93 I used the fresh VM from https://github.com/AndrewDryga/vagrant-box-osx
Tested with clang 8.0 and 8.3. No problems. I guess the root cause is your screwed environment.

**Comment by GeekMe93** [comment]
Thanks for your reply, I used Anaconda’s default environment, I will check later, thanks you very much!

**Comment by vmarkovtsev** [comment]
@qiliux You seem to use Python 2.7 which is unsupported. Nevertheless, I ported the code to Windows and checked that it works.

**Comment by qiliux** [comment]
@vmarkovtsev  Thank you , the error is the ms-compiler. Now it can be installed successfuly with python 3.

**Comment by anlif** [comment]
@GeekMe93 were you able to resolve this? I'm currently having the same issue on OSX 10.11.6.
