### ISSUE TITLE
Assignment matrix reconstruction

### ISSUE THREAD

**Issue by neroksi** [src-d/lapjv#10]
Hi,
Let me tell you guys that this is the fastest python lib I come around with when surfing frenzily on the net looking for THIS python lib that could save me from the scipy slowness (usually algorithms from  scipy lib are very efficient 💯 ) .

Just one headeach, it was a real headeach to figure out how to derive the assignment matrix from **lapjv**'s output. Could you please report in your docstring/readme  that we could get the assignment matrix by doing : 

     x,_, _ = lapjv(cost) 
     row_ind = np.arange(len(x))    
     col_ind = x[row_ind]

Thanks in advance.

**Comment by vmarkovtsev** [comment]
Thanks for the suggestion, I will definitely include this.

**Comment by DXist** [comment]
+1

**Comment by vmarkovtsev** [comment]
Done.
