### ISSUE TITLE
Not working with non-square matrix

### ISSUE THREAD

**Issue by Chocorean** [src-d/lapjv#11]
Hi, I'm trying your implementation in order to replace the `munkres` one for optimizing [a project](https://github.com/usnistgov/ActEV_Scorer).

```
row_ind, col_ind, _ = compute(np.array(cost_matrix))
ValueError: "cost_matrix" must be a square 2D numpy array
```

`cost_matrix` is here a N*M ; Are you going to add this feature ?

Thanks

**Comment by fnando1995** [comment]
Hello, wondering the same.

**Comment by pvnieo** [comment]
same here!

**Comment by vmarkovtsev** [comment]
This is by algorithm design: please tell me how to biject between sets of different cardinality :smile:  If you have a matrix AxB, turn it to a symmetric matrix A+B x A+B with lots of zeros. I should add this to the README.
