### ISSUE TITLE
Inconsistent result for NaNs

### ISSUE THREAD

**Issue by demmerichs** [src-d/lapjv#12]
If I give lapjv a matrix full of `np.nan` then the row_idx vector contains a `-1` but misses the value `n-1` where n is the square matrix size. col_idx on the other hand contains two times the 0 and missing n-2. This is at least the way it is for n=100. This seems highly inconsistent and should be handled by the package, either in deciding to not produce a valid output (all idxs to -1) or producing a fixed assignment (random would be ok, as any assigment would produce NaN total cost). I am not sure how the pattern I observed is achieved through the code and how other edge cases with NaNs and +-Infs are handled, making it handling outside very difficult. E.g. with a few +Inf entries the LAProblem is still well-defined.

Code to reproduce:
```python
from lapjv import lapjv
import numpy as np
print(lapjv(np.zeros((100,100))*np.nan))
```

**Comment by vmarkovtsev** [comment]
NANs officially lead to undefined behavior, and it is the responsibility of the caller to filter them out. I'll add that to the README, thanks!
