### ISSUE TITLE
Install fail on MacOS

### ISSUE THREAD

**Issue by DuckRui** [src-d/lapjv#24]
Hi, I am trying install lapjv on macOS by using command 'pip3 install lapjv', but I got some trouble, like this
![image](https://user-images.githubusercontent.com/41203418/147552849-f344063e-4e5e-4ead-b214-0a113bb305d2.png)
Can you help me? Thank you very much!

**Comment by vmarkovtsev** [comment]
Hi. According to https://developer.apple.com/forums/thread/672654 you are probably building the code on M1. lapjv is strictly x86-64, it doesn't support ARM, including Apple M1. Adding NEON instead of AVX is certainly possible, but I don't have the hardware and time resources in the near future. Sorry!

**Comment by DuckRui** [comment]
> Hi. According to https://developer.apple.com/forums/thread/672654 you are probably building the code on M1. lapjv is strictly x86-64, it doesn't support ARM, including Apple M1. Adding NEON instead of AVX is certainly possible, but I don't have the hardware and time resources in the near future. Sorry!

Actually my mbp is under x86_64, my CPU is Intel Core i5, but I still meet this question = =

**Comment by vmarkovtsev** [comment]
Googling gave me https://github.com/spotify/annoy/issues/523

**Comment by vmarkovtsev** [comment]
Try with `-march=x86-64-v3`?

**Comment by DuckRui** [comment]
> Try with `-march=x86-64-v3`?

Useless.
I download the package lapjv in PyPI and then I tried deleted '-march=native' in setup.py. Now the setup.py is 
![image](https://user-images.githubusercontent.com/41203418/147580272-a430a600-9cc0-4cd8-96dd-accae1739390.png)
Then I run command 'python3 setup.py build' and there are a lot of error = =.
![image](https://user-images.githubusercontent.com/41203418/147580523-ed79c2c3-c2bf-48aa-b7f0-ce6977f0a8de.png)

My clang's version is 
![image](https://user-images.githubusercontent.com/41203418/147580610-1721e505-62a8-4bff-b03d-aa33361b8acb.png)

**Comment by vmarkovtsev** [comment]
This project is using AVX2, so you have to enable a proper machine type, otherwise nothing will compile. `-ftree-vectorize` is something completely different.

I wish I could help here, but unfortunately, I neither have the time resources nor the hardware to debug stuff.

**Comment by dimiterbak** [comment]
I modified setup.py to have:

`
CXX_ARGS = {
    "Darwin": ["-std=c++17", "-mcpu=apple-m1"
`

Now when I run `pip install -e ~/git/lapjv/`

I get the following error:

  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.20.0 in ./venv38/lib/python3.8/site-packages (from lapjv==1.3.21) (1.22.3)
Installing collected packages: lapjv
  Running setup.py develop for lapjv
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [117 lines of output]
        running develop
        running egg_info
        writing manifest file 'lapjv.egg-info/SOURCES.txt'
        running build_ext
        clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/opt/homebrew/opt/openssl@3/include -I/Users/dimitarbakardzhiev/git/kedegit/venv38/lib/python3.8/site-packages/numpy/core/include -I/Users/dimitarbakardzhiev/git/kedegit/venv38/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c python.cc -o build/temp.macosx-10.14-arm64-3.8/python.o -std=c++17 -mcpu=apple-m1 -ftree-vectorize
        In file included from python.cc:6:
        In file included from ./cpuid.h:7:
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/cpuid.h:14:2: error: this header is for x86 only
        #error this header is for x86 only
         ^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/cpuid.h:286:5: error: invalid output constraint '=a' in asm
            __cpuid(__leaf, __eax, __ebx, __ecx, __edx);
            ^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/cpuid.h:251:11: note: expanded from macro '__cpuid'
                : "=a"(__eax), "=r" (__ebx), "=c"(__ecx), "=d"(__edx) \
                  ^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/cpuid.h:301:5: error: invalid output constraint '=a' in asm
            __cpuid(__leaf, *__eax, *__ebx, *__ecx, *__edx);
            ^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/cpuid.h:251:11: note: expanded from macro '__cpuid'
                : "=a"(__eax), "=r" (__ebx), "=c"(__ecx), "=d"(__edx) \
                  ^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/cpuid.h:315:5: error: invalid output constraint '=a' in asm
            __cpuid_count(__leaf, __subleaf, *__eax, *__ebx, *__ecx, *__edx);
            ^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/cpuid.h:258:11: note: expanded from macro '__cpuid_count'
                : "=a"(__eax), "=r" (__ebx), "=c"(__ecx), "=d"(__edx) \
                  ^
        In file included from python.cc:6:
        ./cpuid.h:20:5: error: invalid output constraint '=a' in asm
            CPUID(cpuInfo, 0x00000001);
            ^
        ./cpuid.h:8:27: note: expanded from macro 'CPUID'
          #define CPUID(info, x)  __cpuid_count(x, 0, info[0], info[1], info[2], info[3])
                                  ^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/cpuid.h:258:11: note: expanded from macro '__cpuid_count'
                : "=a"(__eax), "=r" (__ebx), "=c"(__ecx), "=d"(__edx) \
                  ^
        In file included from python.cc:6:
        ./cpuid.h:30:5: error: invalid output constraint '=a' in asm
            CPUID(cpuInfo, 0x00000007);
            ^
        ./cpuid.h:8:27: note: expanded from macro 'CPUID'
          #define CPUID(info, x)  __cpuid_count(x, 0, info[0], info[1], info[2], info[3])
                                  ^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/cpuid.h:258:11: note: expanded from macro '__cpuid_count'
                : "=a"(__eax), "=r" (__ebx), "=c"(__ecx), "=d"(__edx) \
                  ^
        In file included from python.cc:6:
        ./cpuid.h:34:5: error: invalid output constraint '=a' in asm
            CPUID(cpuInfo, 0x80000001);
            ^
        ./cpuid.h:8:27: note: expanded from macro 'CPUID'
          #define CPUID(info, x)  __cpuid_count(x, 0, info[0], info[1], info[2], info[3])
                                  ^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/cpuid.h:258:11: note: expanded from macro '__cpuid_count'
                : "=a"(__eax), "=r" (__ebx), "=c"(__ecx), "=d"(__edx) \
                  ^
        In file included from python.cc:7:
        In file included from ./lap.h:6:
        In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/immintrin.h:13:
        In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/x86gprintrin.h:15:
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/hresetintrin.h:42:27: error: invalid input constraint 'a' in asm
          __asm__ ("hreset $0" :: "a"(__eax));
                                  ^
        In file included from python.cc:7:
        In file included from ./lap.h:6:
        In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/immintrin.h:17:
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:33:5: error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?
            __builtin_ia32_emms();
            ^
        /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/math.h:670:12: note: '__builtin_isless' declared here
            return isless(__lcpp_x, __lcpp_y);
                   ^
        /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/math.h:545:22: note: expanded from macro 'isless'
        #define isless(x, y) __builtin_isless((x),(y))
                             ^
        In file included from python.cc:7:
        In file included from ./lap.h:6:
        In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/immintrin.h:17:
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:33:25: error: too few arguments to function call, expected 2, have 0
            __builtin_ia32_emms();
            ~~~~~~~~~~~~~~~~~~~~^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:50:19: error: use of undeclared identifier '__builtin_ia32_vec_init_v2si'
            return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
                          ^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:67:12: error: use of undeclared identifier '__builtin_ia32_vec_ext_v2si'
            return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
                   ^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:129:19: error: use of undeclared identifier '__builtin_ia32_packsswb'
            return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
                          ^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:159:19: error: use of undeclared identifier '__builtin_ia32_packssdw'
            return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
                          ^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:189:19: error: use of undeclared identifier '__builtin_ia32_packuswb'
            return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
                          ^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:216:19: error: use of undeclared identifier '__builtin_ia32_punpckhbw'
            return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
                          ^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:239:19: error: use of undeclared identifier '__builtin_ia32_punpckhwd'
            return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
                          ^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:260:19: error: use of undeclared identifier '__builtin_ia32_punpckhdq'
            return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
                          ^
        /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:287:19: error: use of undeclared identifier '__builtin_ia32_punpcklbw'
            return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
                          ^
        fatal error: too many errors emitted, stopping now [-ferror-limit=]
        20 errors generated.
        /Users/dimitarbakardzhiev/git/kedegit/venv38/lib/python3.8/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /Users/dimitarbakardzhiev/git/kedegit/venv38/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        error: command '/usr/bin/clang' failed with exit code 1
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
`

**Comment by dimiterbak** [comment]
I pulled the latest changes and run pip install -e ~/git/lapjv/ on MacOS 12.4, M1 chipset, , clang-1316.0.21.2.5

I've got :  clang: error: the clang compiler does not support '-march=haswell'

**Comment by vmarkovtsev** [comment]
No need to do this now, we ship prebuilt macos wheels now.

**Comment by vmarkovtsev** [comment]
That being said, the binaries are tuned for Haswell CPU arch. clang must be modern enough to support it.

**Comment by vmarkovtsev** [comment]
I explicitly mentioned that macOS is not supported in https://github.com/src-d/lapjv/pull/68

M1 builds both for arm64 and x86-64; my custom vectorized code requires AVX2 which apparently is missing on ARM.

Closing this issue; PRs to add macOS support are welcome.
