### ISSUE TITLE
Incorrect results?

### ISSUE THREAD

**Issue by ben-eysenbach** [src-d/lapjv#3]
It appears that this library sometimes returns incorrect results. The example below shows two failure cases. For both problem instances, this library incorrectly assigns both rows to the same column. For reference, I have also included the (presumably correct) results returned by the scipy implementation.

```
import scipy.optimize
import lapjv
import numpy as np

C1 = np.array([[8., 9.],
               [1., 4.]])
C2 = np.array([[5., 1.],
               [8., 9.]])

for C in [C1, C2]:
    print('\n%s' % C)
    print('LAPJV result: %s, %s' % lapjv.lapjv(C)[1:])
    print('Scipy result: %s, %s' % scipy.optimize.linear_sum_assignment(C))
```
Result
```
[[8. 9.]
 [1. 4.]]
LAPJV result: [1 0], [1 0]
Scipy result: [0 1], [1 0]

[[5. 1.]
 [8. 9.]]
LAPJV result: [1 0], [1 0]
Scipy result: [0 1], [1 0]
```
Please let me know if I'm using the library incorrectly, or if there are certain types of inputs to avoid.

**Comment by vmarkovtsev** [comment]
I can reproduce this if I replace `[1:]` with `[:-1]`.

First `[1 0]` means that row 0 goes to column 1 and row 1 goes to column 0.
Second `[1 0]` means that column 0 goes to row 1 and column 1 goes to row 0.

I see no contradiction in the lapjv's result. Not sure about the format which is used by scipy, are they different?

**Comment by ben-eysenbach** [comment]
Thanks @vmarkovtsev! I was interpreting the output format incorrectly.

For reference: gatagat/lap#10

**Comment by HildebrandoBarros** [comment]
Hi guys! Just one question. From this implementation it’s possible to return the dual variables?

**Comment by vmarkovtsev** [comment]
@HildebrandoBarros this is not related to the issue, please open a new one.
