### ISSUE TITLE
Illegal Instruction (core dumped) error

### ISSUE THREAD

**Issue by Reine0017** [src-d/lapjv#4]
May I ask how to solve the "Illegal Instruction (core dumped)" error? I have googled online and checked that avx is one of my flags when I ran lscpu on Ubuntu 16.04 terminal. Here are my specifications:

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
Stepping:              4
CPU MHz:               1530.757
CPU max MHz:           3900.0000
CPU min MHz:           1200.0000
BogoMIPS:              6983.31
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              12288K
NUMA node0 CPU(s):     0-11
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts flush_l1d

Could it be other issues?

**Comment by vmarkovtsev** [comment]
Thanks for bumping this. I have described a workaround in the [README](): you need to `pip3 install git+https://github.com/src-d/lapjv`.

**Comment by Reine0017** [comment]
Thanks a lot for your help. But I have already done this. From terminal:

Collecting git+https://github.com/src-d/lapjv
  Cloning https://github.com/src-d/lapjv to /tmp/pip-req-build-ub1b0io4
Requirement already satisfied (use --upgrade to upgrade): lapjv==1.3.1 from
git+https://github.com/src-d/lapjv in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: numpy in
/usr/local/lib/python3.5/dist-packages (from lapjv==1.3.1) (1.14.2)

May I ask if there's alternative methods?

Warmest Regards,
Reine Fang

**Comment by vmarkovtsev** [comment]
I will see, probably there is a hardcoded optimization flag.

**Comment by Reine0017** [comment]
Thanks a lot!

**Comment by Reine0017** [comment]
Its working now..But I'm not really sure if its because I rebuild my cost_matrix or I installed a new environment (now conda) to run in. Sorry for the trouble.

**Comment by Reine0017** [comment]
Also, your note on the illegal instruction really helped, so thanks!
