### ISSUE TITLE
Installation fail 

### ISSUE THREAD

**Issue by zzjss12** [src-d/lapjv#45]
the command : python -m pip install --upgrade pip
the result :

(DeepBinDif) C:\Users\Acer\Desktop\DeepBinDiff-master>python -m pip install lapjv
Collecting lapjv
  Using cached lapjv-1.3.21.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.20.0 in c:\programdata\anaconda3\envs\deepbindif\lib\site-packages (from lapjv) (1.21.6)
Building wheels for collected packages: lapjv
  Building wheel for lapjv (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'lapjv' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lapjv
  Running setup.py clean for lapjv
Failed to build lapjv
Installing collected packages: lapjv
  Running setup.py install for lapjv ... error
  error: subprocess-exited-with-error

  × Running setup.py install for lapjv did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running install
      C:\ProgramData\Anaconda3\envs\DeepBinDif\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      running build_ext
      building 'lapjv' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lapjv

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by vmarkovtsev** [comment]
> error: Microsoft Visual C++ 14.0 or greater is required.

**Comment by vmarkovtsev** [comment]
We ship prebuilt Windows wheels now.
