### ISSUE TITLE
ERROR: Failed building wheel for lapjv

### ISSUE THREAD

**Issue by km5ar** [src-d/lapjv#50]
how can I fix this error `ERROR: Could not build wheels for lapjv, which is required to install pyproject.toml-based projects`

<img width="991" alt="image" src="https://user-images.githubusercontent.com/54015474/177797171-94052ebb-20a6-430c-b5e4-b93a6846f02e.png">

**Comment by vmarkovtsev** [comment]
I build wheels for 3.8+. Up to 3.10.
