### ISSUE TITLE
Invalid token for CI bot

### ISSUE THREAD

**Issue by patacca** [src-d/lapjv#86]
The `FragileTech/bump-version` action is broken due to invalid authentication, probably because of an invalid token.

See https://github.com/src-d/lapjv/actions/runs/9584495418/job/26428346298#step:4:81
> remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/src-d/lapjv/'

Could you please generate a new valid one so that new releases will be published on pypi?

**Comment by vmarkovtsev** [comment]
On it :+1:

**Comment by vmarkovtsev** [comment]
https://pypi.org/project/lapjv/1.3.25/
